# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MapToGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    #Static assets
    pod 'R.swift', '~> 4.0.0'
    
    #Google services
    pod 'GoogleMaps', '~> 2.6.0'
    pod 'GooglePlaces', '~> 2.6.0'
    #Helpers
    pod 'ReachabilitySwift', '~> 4.1.0'
    
    #Layout
    pod 'SnapKit', '~> 4.0.0'
    
    #UI
    pod 'SwiftMessages', '~> 4.1.2'

#target 'MapToGoTests' do
# inherit! :search_paths
    # Pods for testing
# end

#target 'MapToGoUITests' do
#inherit! :search_paths
    # Pods for testing
    #end

end
